name: Beautiful Jekyll CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 7 * * *"
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the site in the jekyll/builder container
        run: |
          export JEKYLL_VERSION=3.8
          export NOTION_TOKEN=secret_C9mR6Y5ADphkwcnLFnmr8aYYjtWXYQlQTP5kWffhLB6
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          -e PAGES_REPO_NWO=${{ github.repository }} \
          -e NOTION_TOKEN=$NOTION_TOKEN \
          jekyll/builder:$JEKYLL_VERSION /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

name: Jekyll importer

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  importer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: "17"

      - run: npm install

      - run: node _scripts/notion-import.js
        env:
          NOTION_TOKEN: secret_C9mR6Y5ADphkwcnLFnmr8aYYjtWXYQlQTP5kWffhLB6
          DATABASE_ID: 9ad5ca514b5f4aa6893bcf658ad301c8

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: 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
        with:
          commit_message: Update Importer posts
          branch: main
          commit_user_name: importer-bot 🤖
          commit_user_email: actions@github.com
          commit_author: importer-bot 🤖 <actions@github.com>